server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsk2VxIHJgbquBQXhNpO5SaVqzb+3Nv5ogIv+oxDVQ/ebpJwKWmcMq85K+QIS3WBbI8ncaf2in6Yh0x+C1W3rtrbadokjoC8uoM3mmz1HLhx8xPRRLdsDOglX9H7Hjet4xsuJIWHYJO/1mA6Je7YXU23XsmoYU2Psugi+3P4Pb9iP7h8KBdnjBaTiICQDrqxLWfDhBwoYUQkhGPebcAjfdNGFbYJO1ZEHMB2zNK6rBaOtWK0g9xzsWAlNOF82+dtOKwKDT8rpa+nTjKjyfA109PhR8S77FeDL84cCwRoFELQsszDbRmFPYlLyiG+5iXnjxTWN+BI/gvTYG1Jn4Y+wgQIDAQAB
# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml