server:
  port: 8080
  tomcat:
    max-connections: 20
    threads:
      max: 20
      min-spare: 10
    accept-count: 10

# 微信公众号对接
weixin:
  config:
    originalid: gh_39574b099e79
    token: b8b6
    app-id: wxc2aecb7d3d31bb58
    app-secret: 4878d2ce8bcd5b3c485bffb216e18f22
    template_id: 8MHzpB4arY25Xjj5ZFElXFa3tmleCrUj8EGiKDvMJuI

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/s-pay-mall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat

mybatis:
  mapper-locations: classpath:/mybatis/mapper/*.xml
  config-location:  classpath:/mybatis/config/mybatis-config.xml

alipay:
  app_id: 9021000154654929
  merchant_private_key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDIzBGasC98NZx0sgUquiAotfzcWzMWH1Jd54pydhp1Hz/b2bF87Hh1n6uoEVEacH+AEqs4Hq/vMbD5Fp1ZgTTsHsEP+r9aYYWPOxWbigNt/jBihyaacH1Iu957aTlXMtcn72HM0ZaVmT9kVsNyt9kN+FZdUNMlVJDjQWGY1cA4MkvlIfRv158HRm9nR+5aZyFXhdTte3v/Sn0NcX9Y+ffgd2tlbiBuVuO7+DFNQ4+PCKEXQy4lu6gy1E5oylo6A+g2P1bKyI8BhETwHOIa/XoRu5o7+F/a/aMbNerAoxlEvRRcV0nVzkM1tcsHh4a6kbSpyx1Nb+QwrnZGEGf2qvwxAgMBAAECggEBAI6+9Czh34APpMAY5i9vzfjjF3WXqAOsFKQJPJUOfNSSeJVUdyb1/NSxxBhg5yVCoIFtxCbLOgtzafpKJ2Y/wl2xp1Iy0eHwvkAKotvGC5YgRElnBvx3x7jzRcC6Fzd0Pxx2wzIWNVT4cuZj/+IH7NhPmSYRlWlOawoDqtw56MKJS7QZOT+XaTHmrsQ8BRVXpAUjtuyGaQyVmphy9DQX1l6nn+ncJxWx5lwG2zU9Z3+BMJinn2hifkxNfcWcWtATmausIjSlUdhodTrP1ZEuaqlfAHWjdE1qizeqTRJCFc8x8KXLAzlDf4iT6PV6W8Y19AZSIzV1MsCpC8tERg4EZAECgYEA9PIgbudU9LqF0dwq6lWIvzcdAGsKIEOhx/CVGDzYEU+W6DBHaOgLVCjcZUjWUENaSzp0DWW6PbyP/9qJdyUjlJzyjzLwFfBhVCbwmOOkHGs46SaFWAQM2AGE+r67GkNKflln9QaUN/KEIRcCI2yoYSK2nAWbIcOcu3NfWzDhLmECgYEA0dvj1OUSOj5sPAdYWga2AB48KyNoz5Ql8rgwU2wGlthzl7eCFAjuxr4EDYk7NUSqej/jmdqlAzYfU6u0X4j6Vw2zm+I5mzOnHPIR647p0syq+BgkaYU1CNlfU1lrjQQFQKK5TSjGrAnG6h8ZJUbNf+bUoC9r1Ktb1yFU+9YSf9ECgYBT1heRve3PAZRR2th5ciMmx1dO0FQb7OoPg+GT9SdC7YnKGNQoLNvLx1x/8ikgOZ1LCEu2Vi4jeUmUGZlZRUXjVMCUkKup5qd5ZQaOXcPK0kwdSMj08hXvTL3WELf7ajKyAinZrJHIgGIG7VgXBdavwHDd//Ez4j7fzcJCdP1toQKBgCLhhpvjO0VdDMZpfiDwjp20aNHOv+QIvsn6HWYwRWQbNBNamA9WcMGt4aSSU7oF4MQTDHSNJ/JBs7FHj+J1NQ71Iw5c6rBGRJeGEL5zcZ/tDtnPwXWcg3UmFDcZXMwCiBD3Ow99IJCFy38sjhRpEU0aA+tgFm8x0EEQtDxrl4WRAoGBAIUtXJW7x/lo7KBY0Nh6gCZ//e2/50aS3E/RkT0lnwsX5LmdTtMDzSMUW/wrElhkkeTGPCOtOErPJiyLjhR5B2bviIWgcXwTUFsjCMW+39KaohoWxhot1finqICt3nVRrgz2xtAMvzHv6yahUsbdytCWnJcRsI5ZleRkoE22ltE3
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsk2VxIHJgbquBQXhNpO5SaVqzb+3Nv5ogIv+oxDVQ/ebpJwKWmcMq85K+QIS3WBbI8ncaf2in6Yh0x+C1W3rtrbadokjoC8uoM3mmz1HLhx8xPRRLdsDOglX9H7Hjet4xsuJIWHYJO/1mA6Je7YXU23XsmoYU2Psugi+3P4Pb9iP7h8KBdnjBaTiICQDrqxLWfDhBwoYUQkhGPebcAjfdNGFbYJO1ZEHMB2zNK6rBaOtWK0g9xzsWAlNOF82+dtOKwKDT8rpa+nTjKjyfA109PhR8S77FeDL84cCwRoFELQsszDbRmFPYlLyiG+5iXnjxTWN+BI/gvTYG1Jn4Y+wgQIDAQAB
  notify_url: http://s8bcbbc6.natappfree.cc/api/v1/alipay/alipay_notify_url
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  sign_type: RSA2
  charset: utf-8


# 日志
logging:
  level:
    root: info
  config: classpath:logback-spring.xml